<?php
/**
 * @file
 * easyopac_local_material.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function easyopac_local_material_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['facetapi-0NGDoTU308RSgPV0RvS7aUBB3rghPvIn'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0NGDoTU308RSgPV0RvS7aUBB3rghPvIn',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ddbasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ddbasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-0UQXMY0nMHaDOUFQ3cOmAiOK5m3ypuxj'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '0UQXMY0nMHaDOUFQ3cOmAiOK5m3ypuxj',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ddbasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ddbasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-AEsNjofjZ3cZ7yI6WOMO1St5WIaI0yHs'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'AEsNjofjZ3cZ7yI6WOMO1St5WIaI0yHs',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ddbasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ddbasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-Hs0FKlNg8aNisHYsfpyA5BzIYMlyLF1E'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'Hs0FKlNg8aNisHYsfpyA5BzIYMlyLF1E',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ddbasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ddbasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-IjsR3dyuSFuT1hZizgCFW8J0thfGikeg'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'IjsR3dyuSFuT1hZizgCFW8J0thfGikeg',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ddbasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ddbasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['facetapi-UAHNQFUax2u2z9VmPDvG03oj9CnwJhv0'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'UAHNQFUax2u2z9VmPDvG03oj9CnwJhv0',
    'module' => 'facetapi',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'ddbasic' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'ddbasic',
        'weight' => 0,
      ),
      'seven' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'seven',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
